### ISSUE TITLE
asking for the papers

### ISSUE THREAD

**Issue by jm-huang** [sharadnandanwar/snbc#1]
Hello, can you give me the paper which descript this problem? thank you.

my e-mail: hjm.dmir@gmail.com

**Comment by sharadnandanwar** [comment]
Paper titled "Structural Neighborhood based Classification of Nodes in a Network" describing this approach will be appearing at KDD-2016.
A preprint is available at [http://www.kdd.org/kdd2016/papers/files/Paper_679.pdf](http://www.kdd.org/kdd2016/papers/files/Paper_679.pdf).
