### ISSUE TITLE
Error when running SNBC_Run.m

### ISSUE THREAD

**Issue by baldandbrave** [sharadnandanwar/snbc#2]
Hello,
I read your paper on KDD 2016 and downloaded the source code on Github.
When I try to run the example command `[hs mic mac] = SNBC_Run('Datasets/pubmed.mat')`, it threw errors as follow:

> Error using Snowball (line 15)
> Undefined function 'ctranspose' for input arguments of type 'graph'.
> 
> Error in SNBC_Run (line 21)
>     [Test Train] = Snowball(graph, 0.1);

Best wishes.

**Comment by baldandbrave** [comment]
I changed the name of the data from `graph` to `T` and change the parameters `graph` to `T` in SNBC_Run.m, and it ran properly.

**Comment by sharadnandanwar** [comment]
Thanks a lot for letting me know about this :) .
The same issue was reported by other people also. Later, they informed me that the issue was because of using older version of MATLAB.
